# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Multi-Loader Configuration
enabled_platforms=fabric,forge

# Minecraft version target
minecraft_version=1.20.1

# Fabric Properties
# Check these on https://fabricmc.net/develop
fabric_loader_version=0.16.4
fabric_api_version=0.92.7+1.20.1

# Forge version for target Minecraft version
# Check these on https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=1.20.1-47.4.10

# NeoForge version for target Minecraft version
# Check these on https://neoforged.net/
neoforge_version=21.1.150

# Architectury Properties (for mutliloader support)
architectury_plugin_version=3.4-SNAPSHOT
loom_version=1.11-SNAPSHOT

# Mod Properties
mod_version=2.0.0-a7-DEV
maven_group=win.demistorm
archives_base_name=visualhealth

# Mod Menu for Fabric only (still nice to have for Fabric users)
modmenu_version=14.0.0-rc.2
