modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/demistorm/Visual-Health/issues"
license = "GPL-3.0"

[[mods]]
modId = "visual_health"
version = "${version}"
displayName = "Visual Health"
displayURL = "https://github.com/demistorm/Visual-Health"
logoFile = "vh-logo.png"
authors = "Halfstorm"
description = '''
Add visible damage to hurt mobs!

Support me on Ko-Fi: https://ko-fi.com/hstorm

Discord: https://discord.gg/7uttzPbTGq
'''

[[mixins]]
config = "visualhealth.mixins.json"

[[dependencies.visual_health]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.visual_health]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},]"
ordering = "NONE"
side = "CLIENT"
